---
- name: lower directory
  set_fact:
    lower: "{{ project|lower}}"
- name: Parsing Head realase from version
  set_fact:
    head_release: "{{ release |regex_replace('([0-9].[0-9]+).+','\\1')|replace(' ','')}}"
- name: Remove directory
  win_file:
    path: C:\irb\bce\build\{{ lower }}\{{ head_release }}\{{ project }}-sqa{{ release }}.win\
    #path: C:\irb\bce\build\{{ lower }}\{{ head_release }}\
    state: absent
- name: Remove CoreComps
  win_file:
    path: C:\Users\genadmin\CoreComponents\CORECOMPS-sqa{{ release }}
    state: absent
